#!/usr/bin/env bash
for i in {1..20}; do
    if [ $i -eq 4 ]; then
        echo "$i"
        echo "Bad luck from China"
    elif [ $i -eq 9 ]; then
        echo "$i"
        echo "Bad luck from Japan"
    elif [ $i -eq 17 ]; then
        echo "$i"
        echo "Bad luck from Italy"
    else
 
