#!/usr/bin/env bash
# this script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
        if [ $minute -gt 59 ]; then
            ((hour++))
            minute=0
        fi
    done
done | head -n 70
