#!/usr/bin/env bash
# this script gives you information about the holbertonschool file
# Your Bash script should check if the file exists and print:
# if the file exists: holbertonschool file exists
# if the file does not exist: holbertonschool file does not exist
# If the file exists, print:

