#!/usr/bin/env bash
# kills the infinity and beyong program using sigkill signal

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyong" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
 kill -15 "$id"
fi
